#!/bin/bash
set -e

# Fail if env vars missing
: "${APP_DB:?Need to set APP_DB}"
: "${APP_USER:?Need to set APP_USER}"
: "${APP_PASSWORD:?Need to set APP_PASSWORD}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE USER $APP_USER WITH PASSWORD '$APP_PASSWORD';
  CREATE DATABASE $APP_DB OWNER $APP_USER;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB TO $APP_USER;
EOSQL
