# fly.toml app configuration file generated for workflow-nameless-sunset-6743 on 2025-06-21T23:30:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'workflow-nameless-sunset-6743'
primary_region = 'waw'

[build]
  dockerfile = './runner.Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
