# fly.toml app configuration file generated for workflow-billowing-dream-4303 on 2025-06-21T23:24:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'workflow-billowing-dream-4303'
primary_region = 'waw'

[build]
dockerfile = './shard-manager.Dockerfile'

[[vm]]
size = 'shared-cpu-1x'
